# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xen < Formula
  desc "Virtual-monorepo layer for git"
  homepage "https://github.com/sci2sci-opensource/xen"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sci2sci-opensource/xen/releases/download/v0.1.0/xen-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "42497ece6d65bfa23dc16d746c748e31167aeb73933eb376ea8653965d25f85f"

      define_method(:install) do
        bin.install "xen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sci2sci-opensource/xen/releases/download/v0.1.0/xen-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "0d9b4ee874155969ff229a028ac146de814664f04eaa5085bb94384bad597699"

      define_method(:install) do
        bin.install "xen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sci2sci-opensource/xen/releases/download/v0.1.0/xen-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7e083d5fa7403e7d8ebaf3ed2be5e1f0e0c911b3a7d456d3574610400fa77157"
      define_method(:install) do
        bin.install "xen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sci2sci-opensource/xen/releases/download/v0.1.0/xen-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6c886fced4f12659a99881d1090cd2222663df3bc37b76e1e45afc5c98b2f2a4"
      define_method(:install) do
        bin.install "xen"
      end
    end
  end

  test do
    assert_match "xen", shell_output("#{bin}/xen --version")
  end
end
